var demoData = [
	{key:'Afghanistan',value:0,code:'AF',groupKey:'Asia'},
	{key:'United Arab Emirates',value:1,code:'AE',groupKey:'Asia'},
	{key:'Azerbaijan',value:2,code:'AZ',groupKey:'Asia'},
	{key:'Bangladesh',value:3,code:'BD',groupKey:'Asia'},
	{key:'Bahrain',value:4,code:'BH',groupKey:'Asia'},
	{key:'Bhutan',value:5,code:'BT',groupKey:'Asia'},
	{key:'Burma',value:6,code:'MM',groupKey:'Asia'},
	{key:'Cambodia',value:7,code:'KH',groupKey:'Asia'},
	{key:'China',value:8,code:'CN',groupKey:'Asia'},
	{key:'India',value:9,code:'IN',groupKey:'Asia'},
	{key:'Indonesia',value:10,code:'ID',groupKey:'Asia'},
	{key:'Israel',value:11,code:'IL',groupKey:'Asia'},
	{key:'Iraq',value:12,code:'IQ',groupKey:'Asia'},
	{key:'Iran',value:13,code:'IR',groupKey:'Asia'},
	{key:'Japan',value:14,code:'JP',groupKey:'Asia'},
	{key:'Jordan',value:15,code:'JO',groupKey:'Asia'},
	{key:'Kazakhstan',value:16,code:'KZ',groupKey:'Asia'},
	{key:'Kuwait',value:17,code:'KW',groupKey:'Asia'},
	{key:'Laos',value:18,code:'LA',groupKey:'Asia'},
	{key:'Lebanon',value:19,code:'LB',groupKey:'Asia'},
	{key:'Lithuania',value:20,code:'LT',groupKey:'Asia'},
	{key:'Malaysia',value:21,code:'MY',groupKey:'Asia'},
	{key:'Maldives',value:22,code:'MV',groupKey:'Asia'},
	{key:'Mongolia',value:23,code:'MN',groupKey:'Asia'},
	{key:'Macao',value:24,code:'MO',groupKey:'Asia'},
	{key:'Nepal',value:25,code:'NP',groupKey:'Asia'},
	{key:'North Korea',value:26,code:'KR',groupKey:'Asia'},
	{key:'Oman',value:27,code:'OM',groupKey:'Asia'},
	{key:'Pakistan',value:28,code:'PK',groupKey:'Asia'},
	{key:'Philippines',value:29,code:'PH',groupKey:'Asia'},
	{key:'Singapore',value:30,code:'SG',groupKey:'Asia'},
	{key:'South Korea',value:31,code:'KP',groupKey:'Asia'},
	{key:'Sri Lanka',value:32,code:'LK',groupKey:'Asia'},
	{key:'Thailand',value:33,code:'TH',groupKey:'Asia'},
	{key:'Turkey',value:34,code:'TR',groupKey:'Asia'},
	{key:'Vietnam',value:35,code:'VN',groupKey:'Asia'},
	{key:'Brunei',value:36,code:'BN',groupKey:'Asia'},
	{key:'Palestine',value:37,code:'',groupKey:'Asia'},
	{key:'Qatar',value:38,code:'QA',groupKey:'Asia'},
	{key:'Saudi Arabia',value:39,code:'SA',groupKey:'Asia'},
	{key:'Syria',value:40,code:'SY',groupKey:'Asia'},
	{key:'Tadzhikistan',value:41,code:'TJ',groupKey:'Asia'},
	{key:'Turkmenistan',value:42,code:'TM',groupKey:'Asia'},
	{key:'Uzbekistan',value:43,code:'UZ',groupKey:'Asia'},
	{key:'Yemen',value:44,code:'YE',groupKey:'Asia'},
	{key:'Sikkim',value:45,code:'IN-SK',groupKey:'Asia'},
	{key:'Albania',value:46,code:'AL',groupKey:'Europe'},
	{key:'Austria',value:47,code:'AT',groupKey:'Europe'},
	{key:'Belgium',value:48,code:'BE',groupKey:'Europe'},
	{key:'Bulgaria',value:49,code:'BG',groupKey:'Europe'},
	{key:'Croatia',value:50,code:'HR',groupKey:'Europe'},
	{key:'Cyprus',value:51,code:'CY',groupKey:'Europe'},
	{key:'Czech',value:52,code:'CZ ',groupKey:'Europe'},
	{key:'Denmark',value:53,code:'DK',groupKey:'Europe'},
	{key:'Estonia',value:54,code:'EE',groupKey:'Europe'},
	{key:'Finland',value:55,code:'FI',groupKey:'Europe'},
	{key:'France',value:56,code:'FR',groupKey:'Europe'},
	{key:'Germany',value:57,code:'DE',groupKey:'Europe'},
	{key:'Greece',value:58,code:'GR',groupKey:'Europe'},
	{key:'Hungary',value:59,code:'HU',groupKey:'Europe'},
	{key:'Iceland',value:60,code:'IS',groupKey:'Europe'},
	{key:'Ireland',value:61,code:'IE',groupKey:'Europe'},
	{key:'Italy',value:62,code:'IT',groupKey:'Europe'},
	{key:'Liechtenstein',value:63,code:'LI',groupKey:'Europe'},
	{key:'Luxembourg',value:64,code:'LU',groupKey:'Europe'},
	{key:'Latvia',value:65,code:'LV',groupKey:'Europe'},
	{key:'Macedonia',value:66,code:'MKD',groupKey:'Europe'},
	{key:'Malta',value:67,code:'MT',groupKey:'Europe'},
	{key:'Monaco',value:68,code:'MC',groupKey:'Europe'},
	{key:'Moldova',value:69,code:'MD',groupKey:'Europe'},
	{key:'Netherlands',value:70,code:'NL',groupKey:'Europe'},
	{key:'Norway',value:71,code:'NO',groupKey:'Europe'},
	{key:'Poland',value:72,code:'PL',groupKey:'Europe'},
	{key:'Portugal',value:73,code:'PT',groupKey:'Europe'},
	{key:'Romania',value:74,code:'RO',groupKey:'Europe'},
	{key:'Russia',value:75,code:'RU',groupKey:'Europe'},
	{key:'San Marino',value:76,code:'SM',groupKey:'Europe'},
	{key:'Slovenia',value:77,code:'SI',groupKey:'Europe'},
	{key:'Spain',value:78,code:'ES',groupKey:'Europe'},
	{key:'Sweden',value:79,code:'SE',groupKey:'Europe'},
	{key:'Switzerland',value:80,code:'CH',groupKey:'Europe'},
	{key:'Slovakia',value:81,code:'SK',groupKey:'Europe'},
	{key:'United Kingdom',value:82,code:'UK',groupKey:'Europe'},
	{key:'Ukraine',value:83,code:'UA',groupKey:'Europe'},
	{key:'Yugoslavia',value:84,code:'YU',groupKey:'Europe'},
	{key:'Anguilla',value:85,code:'',groupKey:'North America'},
	{key:'Antigua and Barbuda',value:86,code:'',groupKey:'North America'},
	{key:'Barbados',value:87,code:'',groupKey:'North America'},
	{key:'The Bahamas',value:88,code:'BS',groupKey:'North America'},
	{key:'Panama',value:89,code:'PA',groupKey:'North America'},
	{key:'Bermuda',value:90,code:'BM',groupKey:'North America'},
	{key:'Puerto Rico',value:91,code:'',groupKey:'North America'},
	{key:'Belize',value:92,code:'',groupKey:'North America'},
	{key:'Dominican Republic',value:93,code:'',groupKey:'North America'},
	{key:'Dominica',value:94,code:'',groupKey:'North America'},
	{key:'Costa Rica',value:95,code:'CR',groupKey:'North America'},
	{key:'Grenada',value:96,code:'GD',groupKey:'North America'},
	{key:'Greenland',value:97,code:'',groupKey:'North America'},
	{key:'Cuba',value:98,code:'CU',groupKey:'North America'},
	{key:'Guadeloupe',value:99,code:'',groupKey:'North America'},
	{key:'Haiti',value:100,code:'HT',groupKey:'North America'},
	{key:'Honduras',value:101,code:'HN',groupKey:'North America'},
	{key:'Canada',value:102,code:'CA',groupKey:'North America'},
	{key:'Cayman Islands',value:103,code:'',groupKey:'North America'},
	{key:'Martinique',value:104,code:'',groupKey:'North America'},
	{key:'United States',value:105,code:'US',groupKey:'North America'},
	{key:'Mexico',value:106,code:'MX',groupKey:'North America'},
	{key:'Nicaragua',value:107,code:'NI',groupKey:'North America'},
	{key:'El Salvador',value:108,code:'',groupKey:'North America'},
	{key:'St. Kitts',value:109,code:'',groupKey:'North America'},
	{key:'St. Lucia',value:110,code:'',groupKey:'North America'},
	{key:'St. Vincent and the Grenadines',value:111,code:'',groupKey:'North America'},
	{key:'Trinidad and Tobago',value:112,code:'',groupKey:'North America'},
	{key:'Guatemala',value:113,code:'GT',groupKey:'North America'},
	{key:'Virgin Islands',value:114,code:'',groupKey:'North America'},
	{key:'Jamaica',value:115,code:'JM',groupKey:'North America'},
	{key:'Antigua and Barbuda',value:116,code:'',groupKey:'South America'},
	{key:'Argentina',value:117,code:'AR',groupKey:'South America'},
	{key:'Bolivia',value:118,code:'BO',groupKey:'South America'},
	{key:'Brazil',value:119,code:'BR',groupKey:'South America'},
	{key:'Ritish Virgin Islands',value:120,code:'',groupKey:'South America'},
	{key:'Chile',value:121,code:'CL',groupKey:'South America'},
	{key:'Colombia',value:122,code:'CO',groupKey:'South America'},
	{key:'Ecuador',value:123,code:'EC',groupKey:'South America'},
	{key:'Guyana',value:124,code:'GY',groupKey:'South America'},
	{key:'Montserrat',value:125,code:'',groupKey:'South America'},
	{key:'Paraguay',value:126,code:'PY',groupKey:'South America'},
	{key:'Peru',value:127,code:'PE',groupKey:'South America'},
	{key:'Suriname',value:128,code:'',groupKey:'South America'},
	{key:'Urks and Caicos Islands',value:129,code:'',groupKey:'South America'},
	{key:'Uruguay',value:130,code:'UY',groupKey:'South America'},
	{key:'Venezuela',value:131,code:'VE',groupKey:'South America'},
	{key:'American Samoa',value:132,code:'',groupKey:'Pacific'},
	{key:'Australia',value:133,code:'AU',groupKey:'Pacific'},
	{key:'French Polynesia',value:134,code:'',groupKey:'Pacific'},
	{key:'Cook Is.',value:135,code:'CK',groupKey:'Pacific'},
	{key:'Fiji',value:136,code:'FJ',groupKey:'Pacific'},
	{key:'Guam',value:137,code:'GU',groupKey:'Pacific'},
	{key:'Micronesia',value:138,code:'',groupKey:'Pacific'},
	{key:'Nauru',value:139,code:'',groupKey:'Pacific'},
	{key:'N. Mariana Islands',value:140,code:'',groupKey:'Pacific'},
	{key:'New Caledonia',value:141,code:'',groupKey:'Pacific'},
	{key:'New Zealand',value:142,code:'NZ',groupKey:'Pacific'},
	{key:'Papua New Guinea',value:143,code:'PG',groupKey:'Pacific'},
	{key:'Pitcairn Island',value:144,code:'PR',groupKey:'Pacific'},
	{key:'Tonga',value:145,code:'TO',groupKey:'Pacific'},
	{key:'Western Samoa',value:146,code:'WS',groupKey:'Pacific'},
	{key:'Algeria',value:147,code:'DZ',groupKey:'Africa'},
	{key:'Angola',value:148,code:'AO',groupKey:'Africa'},
	{key:'Benin',value:149,code:'BJ',groupKey:'Africa'},
	{key:'Botswana',value:150,code:'BW',groupKey:'Africa'},
	{key:'Burundi',value:151,code:'BI',groupKey:'Africa'},
	{key:'Cameroon',value:152,code:'CM',groupKey:'Africa'},
	{key:'Cape Verde Is.',value:153,code:'CV',groupKey:'Africa'},
	{key:'Central African Republic',value:154,code:'CF',groupKey:'Africa'},
	{key:'Chad',value:155,code:'CHA',groupKey:'Africa'},
	{key:'Congo Rep.',value:156,code:'CG ',groupKey:'Africa'},
	{key:'Djibouti',value:157,code:'DJI',groupKey:'Africa'},
	{key:'Egypt',value:158,code:'EG',groupKey:'Africa'},
	{key:'Equatorial Guinea',value:159,code:'GQ',groupKey:'Africa'},
	{key:'Eritrea',value:160,code:'ENA',groupKey:'Africa'},
	{key:'Ethiopia',value:161,code:'ET',groupKey:'Africa'},
	{key:'Gabon',value:162,code:'GA',groupKey:'Africa'},
	{key:'The Gambia',value:163,code:'GM',groupKey:'Africa'},
	{key:'Ghana',value:164,code:'GH',groupKey:'Africa'},
	{key:'Guinea',value:165,code:'GN',groupKey:'Africa'},
	{key:'Guinea-Bissau',value:166,code:'',groupKey:'Africa'},
	{key:'Kenya',value:167,code:'KE',groupKey:'Africa'},
	{key:'Lesotho',value:168,code:'LST',groupKey:'Africa'},
	{key:'Liberia',value:169,code:'LBR',groupKey:'Africa'},
	{key:'Libya',value:170,code:'LY',groupKey:'Africa'},
	{key:'Madagascar',value:171,code:'MG',groupKey:'Africa'},
	{key:'Malawi',value:172,code:'MW',groupKey:'Africa'},
	{key:'Mali',value:173,code:'ML',groupKey:'Africa'},
	{key:'Mauritius',value:174,code:'MU',groupKey:'Africa'},
	{key:'Mauritania',value:175,code:'MR',groupKey:'Africa'},
	{key:'Morocco',value:176,code:'MA',groupKey:'Africa'},
	{key:'Mozambique',value:177,code:'MZ',groupKey:'Africa'},
	{key:'Namibia',value:178,code:'NA',groupKey:'Africa'},
	{key:'Niger',value:179,code:'NE',groupKey:'Africa'},
	{key:'Nigeria',value:180,code:'NG',groupKey:'Africa'},
	{key:'Reunion',value:181,code:'RO',groupKey:'Africa'},
	{key:'Republic of the Congo',value:182,code:'CG ',groupKey:'Africa'},
	{key:'Rwanda',value:183,code:'RW',groupKey:'Africa'},
	{key:'Sao Tome and Principe',value:184,code:'',groupKey:'Africa'},
	{key:'Senegal',value:185,code:'SN',groupKey:'Africa'},
	{key:'Seychelles',value:186,code:'SC',groupKey:'Africa'},
	{key:'Sierra Leone',value:187,code:'SL',groupKey:'Africa'},
	{key:'Somalia',value:188,code:'SO',groupKey:'Africa'},
	{key:'South Africa',value:189,code:'ZA',groupKey:'Africa'},
	{key:'Sudan',value:190,code:'SD',groupKey:'Africa'},
	{key:'Swaziland',value:191,code:'SZ',groupKey:'Africa'},
	{key:'Tanzania',value:192,code:'TZ',groupKey:'Africa'},
	{key:'Togo',value:193,code:'RT',groupKey:'Africa'},
	{key:'Tunisia',value:194,code:'TN',groupKey:'Africa'},
	{key:'Uganda',value:195,code:'UG',groupKey:'Africa'},
	{key:'Western Sahara',value:196,code:'EH',groupKey:'Africa'},
	{key:'Zambia',value:197,code:'ZM',groupKey:'Africa'},
	{key:'Zimbabwe',value:198,code:'ZW',groupKey:'Africa'},
	{key:'Zaire',value:199,code:'ZR',groupKey:'Africa'}
];
	